version: "3"
services:
  diabetips-api:
    build: .
    image: diabetips-api
    command: npm run start
    environment:
      - NODE_ENV=production
    volumes:
      - "/var/log/diabetips:/home/diabetips-api/logs"
networks:
  default:
    external:
      name: diabetips
