openapi: "3.0.0"
info:
  title: "Diabetips API"
  description: >
    This is the documentation for the Diabetips REST API.
  version: "0.3.0"
  contact:
    email: "contact@diabetips.fr"
servers:
  - url: "https://api.diabetips.fr"
tags:
  - name: "Pagination"
    description: >
      Multitple routes of this API implement pagination, which you can interact with by using the following queries:  
        * `size=X` where X is the size you want the pages to be. 

        Default: 20
        * `page=X` where X is the page you want to GET. 

        First page is found at X=1 (and not X=0).

        Default: 1

      Along with the requested data, the response's header will also contain the key `x-pages` which will hold the
      following information:
        * `previous: X` where X is the previous page of the one requested (if one exists).
        * `next: X` where X is the next page of the one requested (if one exists).
        * `last: X` where X is the last page that can be requested, based on the requested size.

      Routes that implement pagination: 
        [Users](https://docs.diabetips.fr/#tag/Users),
        [Meals](https://docs.diabetips.fr/#tag/Meals),
        [Recipe](https://docs.diabetips.fr/#tag/Recipe),
        [Food](https://docs.diabetips.fr/#tag/Recipe),
        [HbA1C](https://docs.diabetips.fr/#tag/Biometrics),
        [Insulin](https://docs.diabetips.fr/#tag/Biometrics).

  - name: "Authentication"
    description: >
      The Diabetips API uses an OAuth 2.0 based authentication system with JSON Web Tokens. Almost all of this API
      routes require a valid authenticated user access token be passed via the `Authorization: Bearer xyz` HTTP header.


      Tokens can be obtained via the OAuth flow that is most appropriate for your type of application, this API supports
      the following flows:
       * Authorization code
       * Implicit
       * Password
       * Refresh


      See also:
       * [RFC 6749: OAuth 2.0](https://tools.ietf.org/html/rfc6749)
       * [RFC 7519: JSON Web Token](https://tools.ietf.org/html/rfc7519)
  - name: "Users"
  - name: "Connections"
  - name: "Biometrics"
  - name: "Meals"
  - name: "Recipes"
